version: "3"
services:
  db:
    image: mysql:5.6
    volumes:
      - ../volumes/bdd:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: planoo_root_password
      MYSQL_DATABASE: planoo
      MYSQL_USER: planoo_user
      MYSQL_PASSWORD: planoo_password
    ports:
      - "3306:3306"
  planoo:
    depends_on:
      - db
    build: ./docker/images/planoo-apache
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/bo:cached
      - ../volumes/logs/apache2:/var/log/apache2:cached
    extra_hosts:
      planoo.local: 127.0.0.1
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: planoo_root_password
      MYSQL_USER: planoo_user
      MYSQL_PASSWORD: planoo_password
      UPLOAD_LIMIT: 1G
    ports:
      - "8081:80"
