<?php

namespace PromotionBundle\Repository;

/**
 * CommandeCatalogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeCatalogRepository extends \Doctrine\ORM\EntityRepository {

}
