<?php

namespace PromotionBundle\Repository;

/**
 * CouponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponRepository extends \Doctrine\ORM\EntityRepository {

    public function search($data, $page = 0, $max = NULL, $getCount = false, $partner = null) {
        $qb = $this->createQueryBuilder("c");

        if ($getCount) {
            $qb->select('COUNT(c)');
        }

        $qb->leftJoin("c.partner", "partner")
            ->orderBy('c.id', 'DESC');

        $query = isset($data['query']) && $data['query'] ? $data['query'] : null;

        if ($query) {
            $qb->andWhere('partner.nom like :query OR c.name like :query OR c.code like :query')
                ->setParameter('query', "%" . $query . "%")
            ;
        }

        if ($partner) {
            $qb->andWhere('partner.id = :partnerId')
                ->setParameter('partnerId', $partner->getId());
        }

        if ($max) {
            $preparedQuery = $qb->getQuery()
                ->setMaxResults($max)
                ->setFirstResult($page * $max)
            ;
        } else {
            $preparedQuery = $qb->getQuery();
        }

        return $getCount ? $preparedQuery->getSingleScalarResult() : $preparedQuery->getResult();
    }

}
