imports:
  - { resource: config.yml }

framework:
  router:
    resource: "%kernel.root_dir%/config/routing_dev.yml"
    strict_requirements: true
  profiler: { only_exceptions: false }

web_profiler:
  toolbar: true
  intercept_redirects: false

fos_user:
  resetting:
    retry_ttl: 0

monolog:
  handlers:
    console:
      type: console
      bubble: false
      verbosity_levels:
        VERBOSITY_VERBOSE: INFO
        VERBOSITY_VERY_VERBOSE: DEBUG
      channels: ["!doctrine"]
    console_very_verbose:
      type: console
      bubble: false
      verbosity_levels:
        VERBOSITY_VERBOSE: NOTICE
        VERBOSITY_VERY_VERBOSE: NOTICE
        VERBOSITY_DEBUG: DEBUG
      channels: ["doctrine"]
    # uncomment to get logging in your browser
    # you may have to allow bigger header sizes in your Web server configuration
    #firephp:
    #    type:   firephp
    #    level:  info
    #chromephp:
    #    type:   chromephp
    #    level:  info

swiftmailer:
  delivery_address: spool-mail-dev@planoo.dev
  spool:
    type: file
    path: "%kernel.logs_dir%/mail_%kernel.environment%"
