imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: services.yml }
  - { resource: "@BackBundle/Resources/config/services.yml" }
  - { resource: "@BPBundle/Resources/config/services.yml" }
  - { resource: "@PromotionBundle/Resources/config/services.yml" }
  - { resource: "@UserBundle/Resources/config/services.yml" }
  - { resource: "@PaymentBundle/Resources/config/services.yml" }
  - { resource: "@PartnersBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  locale: fr
  blog.posts.latest_post_limit: 3
  cv_directory: "%kernel.project_dir%/web/uploads/cv"

webpack_encore:
  output_path: "%kernel.root_dir%/../web/build/"

framework:
  esi: ~
  translator: { fallbacks: ["%locale%"] }
  secret: "%secret%"
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  form: ~
  csrf_protection: ~
  validation: { enable_annotations: true }
  #serializer:      { enable_annotations: true }
  templating:
    engines: ["twig"]
    #assets_version: SomeVersionScheme
  default_locale: "%locale%"
  trusted_hosts: ~
  session:
    # handler_id set to null will use default session handler from php.ini
    #handler_id:  ~
    handler_id: session.handler.native_file
    save_path: "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    name: IZSESSID
    cookie_domain: "%iz_domain%"
  fragments: ~
  http_method_override: true
  assets: ~

# Twig Configuration
twig:
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  form_themes:
    - bootstrap_3_layout.html.twig
    - _formThemes.html.twig
  globals:
    iz_identification_partner_service: '@PartnersBundle\Service\IzIdentificationPartnerService'
    iz_partner_list_service: '@PartnersBundle\Service\IzPartnerListService'
    white_mark: "%white_mark%"
    white_mark_brand: "%white_mark_brand%"
    zopim_key: "%zopim_key%"
    ga_tracking: "%ga_tracking%"
    gtm_id: "%gtm_id%"
    stripe_publishable_key: "%stripe_publishable_key%"
    iz_domain: "%iz_domain%"

# Doctrine Configuration
doctrine:
  dbal:
    driver: pdo_mysql
    host: "%database_host%"
    port: "%database_port%"
    dbname: "%database_name%"
    user: "%database_user%"
    password: "%database_password%"
    charset: UTF8
    # if using pdo_sqlite as your database driver:
    #   1. add the path in parameters.yml
    #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
    #   2. Uncomment database_path in parameters.yml.dist
    #   3. Uncomment next line:
    #     path:     "%database_path%"

  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    #        naming_strategy: doctrine.orm.naming_strategy.underscore
    entity_managers:
      default:
        filters:
          softdeleteable:
            class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
            enabled: true
        auto_mapping: true
        mappings:
          gedmo_translatable:
            type: annotation
            prefix: Gedmo\Translatable\Entity
            dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
            alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
            is_bundle: false
          gedmo_translator:
            type: annotation
            prefix: Gedmo\Translator\Entity
            dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
            alias: GedmoTranslator # (optional) it will default to the name set for the mapping
            is_bundle: false
          gedmo_loggable:
            type: annotation
            prefix: Gedmo\Loggable\Entity
            dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
            alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
            is_bundle: false
          gedmo_tree:
            type: annotation
            prefix: Gedmo\Tree\Entity
            dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
            alias: GedmoTree # (optional) it will default to the name set for the mapping
            is_bundle: false
        dql:
          string_functions:
            datediff: Doctrine\ORM\Query\AST\Functions\DateDiffFunction

# Swiftmailer Configuration
swiftmailer:
  transport: "%mailer_transport%"
  host: "%mailer_host%"
  #username:  "%mailer_user%" //configuration par déclaration d'IP https://admin.google.com/planoo.ai/AdminHome?hl=fr#ServiceSettings/notab=1&service=email&subtab=filters
  #password:  "%mailer_password%"
  encryption: tls
  port: 587
  local_domain: "%mailer_domain%"
  spool: { type: memory }

# FOSUser Configuration
fos_user:
  db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
  firewall_name: main
  user_class: UserBundle\Entity\User
  registration:
    confirmation:
      enabled: false # change to true for required email confirmation
      #template:   FOSUserBundle:Registration:email.txt.twig
    form:
      type: BackBundle\Form\RegistrationType
      validation_groups: [AcmeRegistration]
  resetting:
    token_ttl: 86400
    email:
      template: FOSUserBundle:Resetting:email.txt.twig
    #form:
    #type:               fos_user_resetting
  from_email:
    address: "noreply@%mailer_domain%"
    sender_name: "Planoo.ai"
  profile:
    form:
      type: UserBundle\Form\ProfileType
      validation_groups: [AcmeProfile]

# A2lixTranslationFormBundle Configuration
a2lix_translation_form:
  locale_provider: default # [1]
  locales: [fr, en, es, de] # [1-a]
  default_locale: fr # [1-b]
  required_locales: [fr] # [1-c]
  templating: "A2lixTranslationFormBundle::default.html.twig" # [2]

# fos_js_routing Configuration
fos_js_routing:
  routes_to_expose: [promotion_catalog_add_item, promotion_catalog_remove_item]

# Paginator Configuration
knp_paginator:
  page_range: 5 # default page range used in pagination control
  default_options:
    page_name: page # page query parameter name
    sort_field_name: sort # sort field query parameter name
    sort_direction_name: direction # sort direction query parameter name
    distinct: true # ensure distinct results, useful when ORM queries are using GROUP BY statements
  template:
    pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig # sliding pagination controls template
    sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

monolog:
  handlers:
    login:
      type: rotating_file
      max_files: 30
      path: "%kernel.logs_dir%/%kernel.environment%.auth.log"
      level: info
      channels: security

    main_error:
      type: fingers_crossed
      action_level: error
      handler: streamed_error
    streamed_error:
      type: rotating_file
      max_files: 30
      path: "%kernel.logs_dir%/%kernel.environment%.error.log"
      level: warning

    main_critical:
      type: fingers_crossed
      action_level: critical
      handler: grouped_critical
    grouped_critical:
      type: group
      members: [streamed_critical, buffered_critical]
    streamed_critical:
      type: rotating_file
      max_files: 30
      path: "%kernel.logs_dir%/%kernel.environment%.critical.log"
      level: info
    buffered_critical:
      type: buffer
      handler: swift_critical
    swift_critical:
      type: swift_mailer
      from_email: critical-error@%mailer_domain%
      to_email: technical-support@planoo.ai
      subject: Une erreur critique est survenue !
      level: info
