<?php

namespace UserBundle\Repository;

/**
 * SocialChargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialChargeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestUsers($limit = null)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->orderBy('u.createdAt', 'DESC')
        ;

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
            ->getResult();
    }
}
