financial_investissement_index:
    path:     /step.html
    methods:  [GET]
    defaults: { _controller: BPBundle:Frontend/Default:investissement }

financial_investissement_update:
    path:        /{id}
    methods:     [PUT]
    controller:  BPBundle:Frontend/Investissement:update
    requirements:
        id: '[0-9]*'
        
financial_investissement_create:
    path:        /{idBusinessPlan}
    methods:     [POST]
    controller:  BPBundle:Frontend/Investissement:create
    requirements:
        idBusinessPlan: '[0-9]*'

financial_investissement_delete:
    path:        /{id}
    methods:     [DELETE]
    controller:  BPBundle:Frontend/Investissement:delete
    requirements:
        id: '[0-9]*'
    
financial_investissement_show:
    path:        /{id}
    methods:     [GET]
    controller:  BPBundle:Frontend/Investissement:show
    requirements:
        id: '[0-9]*'
    
financial_investissement_list:
    path:        /list.{_format}
    methods:     [GET]
    controller:  BPBundle:Frontend/Investissement:list
    defaults:
        _format: json
    requirements:
        _format:  html|json

financial_investissement_add_form:
    path:        /{idBusinessPlan}/add.html
    methods:     [GET]
    controller:  BPBundle:Frontend/Investissement:getAddForm
    requirements:
        idBusinessPlan: '[0-9]*'
        
financial_investissement_edit_form:
    path:        /{id}/edit.html
    methods:     [GET]
    controller:  BPBundle:Frontend/Investissement:getEditForm
    requirements:
        id: '[0-9]*'