<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20180317135330 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE ext_translations (id INT AUTO_INCREMENT NOT NULL, locale VARCHAR(8) NOT NULL, object_class VARCHAR(255) NOT NULL, field VARCHAR(32) NOT NULL, foreign_key VARCHAR(64) NOT NULL, content LONGTEXT DEFAULT NULL, INDEX translations_lookup_idx (locale, object_class, foreign_key), UNIQUE INDEX lookup_unique_idx (locale, object_class, field, foreign_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ext_log_entries (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(8) NOT NULL, logged_at DATETIME NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(255) NOT NULL, version INT NOT NULL, data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', username VARCHAR(255) DEFAULT NULL, INDEX log_class_lookup_idx (object_class), INDEX log_date_lookup_idx (logged_at), INDEX log_user_lookup_idx (username), INDEX log_version_lookup_idx (object_id, object_class, version), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE back_benefit (id INT AUTO_INCREMENT NOT NULL, catalog_id INT DEFAULT NULL, fontColor VARCHAR(100) DEFAULT NULL, bgColor VARCHAR(100) DEFAULT NULL, UNIQUE INDEX UNIQ_87E1E301CC3C66FC (catalog_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE back_benefit_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, name VARCHAR(150) NOT NULL, detail LONGTEXT NOT NULL, postScriptum VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_15B275912C2AC5D3 (translatable_id), UNIQUE INDEX back_benefit_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE back_concept (id INT AUTO_INCREMENT NOT NULL, video VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE back_concept_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_5ADDF0F72C2AC5D3 (translatable_id), UNIQUE INDEX back_concept_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE back_contact (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(255) NOT NULL, message LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE back_definition (id INT AUTO_INCREMENT NOT NULL, concept_id INT DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, INDEX IDX_A6BC8910F909284E (concept_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE back_definition_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, content LONGTEXT DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_E91481A62C2AC5D3 (translatable_id), UNIQUE INDEX back_definition_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE back_document (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, country_id INT DEFAULT NULL, name VARCHAR(150) NOT NULL, description LONGTEXT DEFAULT NULL, doc VARCHAR(255) DEFAULT NULL, slug VARCHAR(128) NOT NULL, UNIQUE INDEX UNIQ_22BDDDF6989D9B62 (slug), INDEX IDX_22BDDDF64584665A (product_id), INDEX IDX_22BDDDF6F92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE back_page (id INT AUTO_INCREMENT NOT NULL, image VARCHAR(255) DEFAULT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, deletedAt DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE back_page_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, title VARCHAR(150) NOT NULL, content LONGTEXT NOT NULL, slug VARCHAR(128) NOT NULL, locale VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_9DB75F3B989D9B62 (slug), INDEX IDX_9DB75F3B2C2AC5D3 (translatable_id), UNIQUE INDEX back_page_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE back_partner (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(150) NOT NULL, websiteLink VARCHAR(1024) NOT NULL, description LONGTEXT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, slug VARCHAR(128) NOT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, deletedAt DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_EA41DD08989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE back_press (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, image VARCHAR(255) DEFAULT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, deletedAt DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE back_product (id INT AUTO_INCREMENT NOT NULL, link VARCHAR(255) DEFAULT NULL, published TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE back_product_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, title VARCHAR(150) NOT NULL, content LONGTEXT DEFAULT NULL, description LONGTEXT DEFAULT NULL, slug VARCHAR(128) NOT NULL, locale VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_132F6B69989D9B62 (slug), INDEX IDX_132F6B692C2AC5D3 (translatable_id), UNIQUE INDEX back_product_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE back_testimonials (id INT AUTO_INCREMENT NOT NULL, content LONGTEXT NOT NULL, author VARCHAR(50) NOT NULL, createdAt DATETIME NOT NULL, note VARCHAR(255) NOT NULL, image VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE back_introsection (id INT AUTO_INCREMENT NOT NULL, content LONGTEXT DEFAULT NULL, image VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, sub_title VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, slug VARCHAR(128) NOT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, deletedAt DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_72113DE6989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_post (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, author VARCHAR(255) DEFAULT NULL, tags VARCHAR(255) DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, deletedAt DATETIME DEFAULT NULL, INDEX IDX_BA5AE01D12469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT DEFAULT NULL, slug VARCHAR(128) NOT NULL, locale VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_5829CF40989D9B62 (slug), INDEX IDX_5829CF402C2AC5D3 (translatable_id), UNIQUE INDEX post_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_address (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, country_id INT DEFAULT NULL, street VARCHAR(255) NOT NULL, code_postal VARCHAR(10) NOT NULL, city VARCHAR(50) NOT NULL, INDEX IDX_DA1F2E7BA76ED395 (user_id), INDEX IDX_DA1F2E7BF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_amortissement (id_charge_label INT NOT NULL, id_country INT NOT NULL, duree DOUBLE PRECISION DEFAULT NULL, INDEX IDX_39D8AEA43B4229B2 (id_charge_label), INDEX IDX_39D8AEA48DEE6016 (id_country), PRIMARY KEY(id_charge_label, id_country)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_bfr (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, customer DOUBLE PRECISION NOT NULL, provider DOUBLE PRECISION NOT NULL, acpte_customer DOUBLE PRECISION NOT NULL, acpte_provider DOUBLE PRECISION NOT NULL, stock DOUBLE PRECISION NOT NULL, businessPlan_id INT DEFAULT NULL, INDEX IDX_58BD33B6A76ED395 (user_id), UNIQUE INDEX UNIQ_58BD33B685B7937E (businessPlan_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_bp (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, service_id INT NOT NULL, reference VARCHAR(255) DEFAULT NULL, name VARCHAR(150) DEFAULT NULL, document VARCHAR(255) DEFAULT NULL, state VARCHAR(150) DEFAULT NULL, steps LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', slug VARCHAR(128) NOT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, deletedAt DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_2EC16238989D9B62 (slug), INDEX IDX_2EC16238A76ED395 (user_id), UNIQUE INDEX UNIQ_2EC16238ED5CA9E6 (service_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_cart (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, coupon_id INT DEFAULT NULL, payment_id INT DEFAULT NULL, businessPlan_id INT DEFAULT NULL, INDEX IDX_1AC380C2A76ED395 (user_id), INDEX IDX_1AC380C285B7937E (businessPlan_id), INDEX IDX_1AC380C266C5951B (coupon_id), UNIQUE INDEX UNIQ_1AC380C24C3A3BB (payment_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_charge (id INT AUTO_INCREMENT NOT NULL, otherChoice VARCHAR(255) DEFAULT NULL, taux DOUBLE PRECISION DEFAULT NULL, businessPlan_id INT DEFAULT NULL, chargeLabel_id INT DEFAULT NULL, INDEX IDX_9F8B0D585B7937E (businessPlan_id), INDEX IDX_9F8B0D5EA6C58B7 (chargeLabel_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_charge_label (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(255) NOT NULL, classement VARCHAR(255) NOT NULL, is_interet TINYINT(1) NOT NULL, is_remboursable TINYINT(1) NOT NULL, is_non_remboursable TINYINT(1) NOT NULL, is_emprunt_bancaire TINYINT(1) NOT NULL, is_compte_courant_associe TINYINT(1) NOT NULL, is_remboursement_courant_associe TINYINT(1) NOT NULL, is_augmentation_capital TINYINT(1) NOT NULL, id_dividende TINYINT(1) NOT NULL, deletedAt DATETIME DEFAULT NULL, display_taux TINYINT(1) NOT NULL, display_duree TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_charge_label_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_482B3EC52C2AC5D3 (translatable_id), UNIQUE INDEX bp_charge_label_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_country (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(3) NOT NULL, name VARCHAR(255) NOT NULL, flag VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_exercice (id INT AUTO_INCREMENT NOT NULL, dateDebut DATETIME DEFAULT NULL, dateFin DATETIME DEFAULT NULL, businessPlan_id INT DEFAULT NULL, INDEX IDX_B9A78D0E85B7937E (businessPlan_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_funding (id INT AUTO_INCREMENT NOT NULL, created_at DATETIME NOT NULL, within INT NOT NULL, amount DOUBLE PRECISION NOT NULL, rate DOUBLE PRECISION NOT NULL, businessPlan_id INT DEFAULT NULL, chargeLabel_id INT DEFAULT NULL, INDEX IDX_45C902C85B7937E (businessPlan_id), INDEX IDX_45C902CEA6C58B7 (chargeLabel_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_income (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, name VARCHAR(150) NOT NULL, sale LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', single_price LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', cost LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', untitled VARCHAR(150) DEFAULT NULL, commission LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', directCost VARCHAR(150) DEFAULT NULL, businessPlan_id INT DEFAULT NULL, INDEX IDX_633B7631A76ED395 (user_id), INDEX IDX_633B763185B7937E (businessPlan_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_info_charge (id INT AUTO_INCREMENT NOT NULL, exercice_id INT DEFAULT NULL, charge_id INT DEFAULT NULL, cout DOUBLE PRECISION DEFAULT NULL, INDEX IDX_BB22C13489D40298 (exercice_id), INDEX IDX_BB22C13455284914 (charge_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_info_product (id INT AUTO_INCREMENT NOT NULL, produit_id INT DEFAULT NULL, exercice_id INT DEFAULT NULL, nbVente INT NOT NULL, prixVente DOUBLE PRECISION NOT NULL, cout DOUBLE PRECISION NOT NULL, commission DOUBLE PRECISION DEFAULT NULL, INDEX IDX_D3A44DC8F347EFB (produit_id), INDEX IDX_D3A44DC889D40298 (exercice_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_information (id INT AUTO_INCREMENT NOT NULL, location_id INT DEFAULT NULL, address_id INT DEFAULT NULL, user_id INT DEFAULT NULL, name_corporate VARCHAR(100) NOT NULL, firstname_owner VARCHAR(100) NOT NULL, lastname_owner VARCHAR(100) NOT NULL, logo VARCHAR(255) DEFAULT NULL, job VARCHAR(150) NOT NULL, franchise TINYINT(1) DEFAULT \'0\' NOT NULL, name_franchise VARCHAR(150) DEFAULT NULL, capital DOUBLE PRECISION DEFAULT NULL, accounting_period INT DEFAULT NULL, created_at DATETIME DEFAULT NULL, closing_date DATETIME DEFAULT NULL, tva INT DEFAULT NULL, businessPlan_id INT DEFAULT NULL, legalForm_id INT DEFAULT NULL, INDEX IDX_AED22D564D218E (location_id), UNIQUE INDEX UNIQ_AED22D5F5B7AF75 (address_id), INDEX IDX_AED22D5A76ED395 (user_id), UNIQUE INDEX UNIQ_AED22D585B7937E (businessPlan_id), INDEX IDX_AED22D5854E9F19 (legalForm_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_investissement (id INT AUTO_INCREMENT NOT NULL, date DATETIME NOT NULL, amount DOUBLE PRECISION NOT NULL, chargeLabel_id INT DEFAULT NULL, businessPlan_id INT DEFAULT NULL, INDEX IDX_21C9504EA6C58B7 (chargeLabel_id), INDEX IDX_21C950485B7937E (businessPlan_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_legal_form (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, code VARCHAR(5) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE legal_form_country (id_legal_form INT NOT NULL, id_country INT NOT NULL, INDEX IDX_B507BD1EDA79932F (id_legal_form), INDEX IDX_B507BD1E8DEE6016 (id_country), PRIMARY KEY(id_legal_form, id_country)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_location (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, flag VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, step INT DEFAULT NULL, info LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_pole_staff (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pole_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_19E38852C2AC5D3 (translatable_id), UNIQUE INDEX pole_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_produit (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, nameCommission VARCHAR(100) DEFAULT NULL, businessPlan_id INT DEFAULT NULL, INDEX IDX_FEF4ADDD85B7937E (businessPlan_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_rate (id INT AUTO_INCREMENT NOT NULL, type_id INT DEFAULT NULL, country_id INT DEFAULT NULL, value DOUBLE PRECISION NOT NULL, base VARCHAR(255) NOT NULL, base_min DOUBLE PRECISION NOT NULL, base_max DOUBLE PRECISION DEFAULT NULL, assiette_ca DOUBLE PRECISION DEFAULT NULL, INDEX IDX_CE8C374CC54C8C93 (type_id), INDEX IDX_CE8C374CF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_rate_label (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_saisonnalite (id INT AUTO_INCREMENT NOT NULL, nomMois VARCHAR(255) DEFAULT NULL, saisonCA DOUBLE PRECISION DEFAULT NULL, businessPlan_id INT DEFAULT NULL, INDEX IDX_DB3F488B85B7937E (businessPlan_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_service (id INT AUTO_INCREMENT NOT NULL, expire_edit_date DATETIME DEFAULT NULL, advice_hour INT NOT NULL, expert_advice INT NOT NULL, expert_review INT NOT NULL, bpCatalogKind_id INT DEFAULT NULL, INDEX IDX_36CCDB28FC33D2FD (bpCatalogKind_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_smic (id INT AUTO_INCREMENT NOT NULL, montant DOUBLE PRECISION NOT NULL, coef DOUBLE PRECISION NOT NULL, cice DOUBLE PRECISION NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_staff (id INT AUTO_INCREMENT NOT NULL, pole_id INT DEFAULT NULL, status_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, income DOUBLE PRECISION NOT NULL, created_at DATETIME NOT NULL, finished_at DATETIME DEFAULT NULL, hours INT DEFAULT NULL, businessPlan_id INT DEFAULT NULL, INDEX IDX_6210162985B7937E (businessPlan_id), INDEX IDX_62101629419C3385 (pole_id), INDEX IDX_621016296BF700BD (status_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bp_status (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE status_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_B0B3309E2C2AC5D3 (translatable_id), UNIQUE INDEX status_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE promotion_catalog (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, price DOUBLE PRECISION DEFAULT NULL, isFormule TINYINT(1) NOT NULL, isSmallBP TINYINT(1) NOT NULL, nb_day_expire_edit_date INT NOT NULL, nb_advice_hour INT NOT NULL, nb_expert_advice INT NOT NULL, expert_review INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE join_cart_catalog (id INT AUTO_INCREMENT NOT NULL, cart_id INT DEFAULT NULL, catalog_id INT DEFAULT NULL, quantity INT NOT NULL, INDEX IDX_F95EC5191AD5CDBF (cart_id), INDEX IDX_F95EC519CC3C66FC (catalog_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE promotion_coupon (id INT AUTO_INCREMENT NOT NULL, partner_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, used INT DEFAULT NULL, maxUsed INT DEFAULT NULL, starts_at DATETIME DEFAULT NULL, ends_at DATETIME DEFAULT NULL, minimumAmount DOUBLE PRECISION DEFAULT NULL, couponRange VARCHAR(255) DEFAULT NULL, kind VARCHAR(255) NOT NULL, couponValue DOUBLE PRECISION NOT NULL, sentDate DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_7105143F77153098 (code), INDEX IDX_7105143F9393F8FE (partner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE coupon_user (coupon_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_CDAD0A4B66C5951B (coupon_id), INDEX IDX_CDAD0A4BA76ED395 (user_id), PRIMARY KEY(coupon_id, user_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_social_charge (id INT AUTO_INCREMENT NOT NULL, country_id INT DEFAULT NULL, status_id INT DEFAULT NULL, chargeSalariale DOUBLE PRECISION NOT NULL, chargePatronale DOUBLE PRECISION NOT NULL, cice DOUBLE PRECISION NOT NULL, INDEX IDX_A5AE6BB8F92F3E70 (country_id), INDEX IDX_A5AE6BB86BF700BD (status_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_user (id INT AUTO_INCREMENT NOT NULL, partner_id INT DEFAULT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', stripeId VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_F7129A8092FC23A8 (username_canonical), UNIQUE INDEX UNIQ_F7129A80A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_F7129A80C05FB297 (confirmation_token), INDEX IDX_F7129A809393F8FE (partner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pitch_business_model (id INT AUTO_INCREMENT NOT NULL, pitch_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, price DOUBLE PRECISION NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_7FEB5156FEEFC64B (pitch_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pitch_cart (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, pitch_id INT DEFAULT NULL, card VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, month VARCHAR(255) NOT NULL, year VARCHAR(255) NOT NULL, cvc VARCHAR(255) NOT NULL, service VARCHAR(255) NOT NULL, stripe_token VARCHAR(255) NOT NULL, INDEX IDX_3449185A76ED395 (user_id), UNIQUE INDEX UNIQ_3449185FEEFC64B (pitch_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pitch_competitor (id INT AUTO_INCREMENT NOT NULL, concurrence_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, logo VARCHAR(255) NOT NULL, firstValue DOUBLE PRECISION NOT NULL, secondValue DOUBLE PRECISION NOT NULL, INDEX IDX_812C40C6808BBBF5 (concurrence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pitch_concurrence (id INT AUTO_INCREMENT NOT NULL, pitch_id INT DEFAULT NULL, indicatorOneLabel VARCHAR(255) NOT NULL, indicatorOneValue DOUBLE PRECISION NOT NULL, indicatorTwoLabel VARCHAR(255) NOT NULL, indicatorTwoValue DOUBLE PRECISION NOT NULL, UNIQUE INDEX UNIQ_4AEC9B0FFEEFC64B (pitch_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pitch_indicator (id INT AUTO_INCREMENT NOT NULL, pitch_id INT DEFAULT NULL, name1 VARCHAR(255) NOT NULL, name2 VARCHAR(255) NOT NULL, name3 VARCHAR(255) NOT NULL, name4 VARCHAR(255) NOT NULL, quantity1 DOUBLE PRECISION NOT NULL, quantity2 DOUBLE PRECISION NOT NULL, quantity3 DOUBLE PRECISION NOT NULL, quantity4 DOUBLE PRECISION NOT NULL, unity1 VARCHAR(255) NOT NULL, unity2 VARCHAR(255) NOT NULL, unity3 VARCHAR(255) NOT NULL, unity4 VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_43B0226DFEEFC64B (pitch_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pitch_information (id INT AUTO_INCREMENT NOT NULL, pitch_id INT DEFAULT NULL, enterprise VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, owner VARCHAR(255) DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, color VARCHAR(255) DEFAULT NULL, concept LONGTEXT DEFAULT NULL, market LONGTEXT DEFAULT NULL, target LONGTEXT DEFAULT NULL, trust LONGTEXT DEFAULT NULL, size_market LONGTEXT DEFAULT NULL, legalForm_id INT DEFAULT NULL, INDEX IDX_6D1CCC8B854E9F19 (legalForm_id), UNIQUE INDEX UNIQ_6D1CCC8BFEEFC64B (pitch_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pitch (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, document VARCHAR(255) DEFAULT NULL, slug VARCHAR(128) NOT NULL, state VARCHAR(255) DEFAULT NULL, price DOUBLE PRECISION DEFAULT NULL, step INT DEFAULT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, deletedAt DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_279FBED95E237E06 (name), UNIQUE INDEX UNIQ_279FBED9989D9B62 (slug), INDEX IDX_279FBED9A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE promotion_catalog_pitch (pitch_id INT NOT NULL, catalog_id INT NOT NULL, INDEX IDX_7E3591FFEEFC64B (pitch_id), INDEX IDX_7E3591FCC3C66FC (catalog_id), PRIMARY KEY(pitch_id, catalog_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pitch_strategy (id INT AUTO_INCREMENT NOT NULL, pitch_id INT DEFAULT NULL, communication LONGTEXT NOT NULL, rh LONGTEXT NOT NULL, customer LONGTEXT NOT NULL, development LONGTEXT NOT NULL, UNIQUE INDEX UNIQ_42770021FEEFC64B (pitch_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pitch_swot (id INT AUTO_INCREMENT NOT NULL, pitch_id INT DEFAULT NULL, strength_description LONGTEXT NOT NULL, strength_resume VARCHAR(255) NOT NULL, weakness_description LONGTEXT NOT NULL, weakness_resume VARCHAR(255) NOT NULL, opportunity_description LONGTEXT NOT NULL, opportunity_resume VARCHAR(255) NOT NULL, menace_description LONGTEXT NOT NULL, menace_resume VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_B49A75C4FEEFC64B (pitch_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pitch_team (id INT AUTO_INCREMENT NOT NULL, pitch_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, familyName VARCHAR(255) NOT NULL, job VARCHAR(100) NOT NULL, createdAt DATETIME DEFAULT NULL, description LONGTEXT DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, INDEX IDX_CC07BF2DFEEFC64B (pitch_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment (id INT AUTO_INCREMENT NOT NULL, stripe_token VARCHAR(255) NOT NULL, cartId VARCHAR(255) NOT NULL, amount DOUBLE PRECISION NOT NULL, paymentDate DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE partners_partner (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(64) NOT NULL, customDomain VARCHAR(128) NOT NULL, logo LONGBLOB DEFAULT NULL, cobrandingLogo LONGBLOB DEFAULT NULL, UNIQUE INDEX UNIQ_42672866E9300FC8 (customDomain), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lexik_translation_file (id INT AUTO_INCREMENT NOT NULL, domain VARCHAR(255) NOT NULL, locale VARCHAR(10) NOT NULL, extention VARCHAR(10) NOT NULL, path VARCHAR(255) NOT NULL, hash VARCHAR(255) NOT NULL, UNIQUE INDEX hash_idx (hash), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lexik_trans_unit_translations (id INT AUTO_INCREMENT NOT NULL, file_id INT DEFAULT NULL, trans_unit_id INT DEFAULT NULL, locale VARCHAR(10) NOT NULL, content LONGTEXT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_B0AA394493CB796C (file_id), INDEX IDX_B0AA3944C3C583C9 (trans_unit_id), UNIQUE INDEX trans_unit_locale_idx (trans_unit_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lexik_trans_unit (id INT AUTO_INCREMENT NOT NULL, key_name VARCHAR(255) NOT NULL, domain VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX key_domain_idx (key_name, domain), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE back_benefit ADD CONSTRAINT FK_87E1E301CC3C66FC FOREIGN KEY (catalog_id) REFERENCES promotion_catalog (id)');
        $this->addSql('ALTER TABLE back_benefit_translation ADD CONSTRAINT FK_15B275912C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES back_benefit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE back_concept_translation ADD CONSTRAINT FK_5ADDF0F72C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES back_concept (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE back_definition ADD CONSTRAINT FK_A6BC8910F909284E FOREIGN KEY (concept_id) REFERENCES back_concept (id)');
        $this->addSql('ALTER TABLE back_definition_translation ADD CONSTRAINT FK_E91481A62C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES back_definition (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE back_document ADD CONSTRAINT FK_22BDDDF64584665A FOREIGN KEY (product_id) REFERENCES back_product (id)');
        $this->addSql('ALTER TABLE back_document ADD CONSTRAINT FK_22BDDDF6F92F3E70 FOREIGN KEY (country_id) REFERENCES bp_country (id)');
        $this->addSql('ALTER TABLE back_page_translation ADD CONSTRAINT FK_9DB75F3B2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES back_page (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE back_product_translation ADD CONSTRAINT FK_132F6B692C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES back_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE blog_post ADD CONSTRAINT FK_BA5AE01D12469DE2 FOREIGN KEY (category_id) REFERENCES blog_category (id)');
        $this->addSql('ALTER TABLE post_translation ADD CONSTRAINT FK_5829CF402C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES blog_post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bp_address ADD CONSTRAINT FK_DA1F2E7BA76ED395 FOREIGN KEY (user_id) REFERENCES user_user (id)');
        $this->addSql('ALTER TABLE bp_address ADD CONSTRAINT FK_DA1F2E7BF92F3E70 FOREIGN KEY (country_id) REFERENCES bp_country (id)');
        $this->addSql('ALTER TABLE bp_amortissement ADD CONSTRAINT FK_39D8AEA43B4229B2 FOREIGN KEY (id_charge_label) REFERENCES bp_charge_label (id)');
        $this->addSql('ALTER TABLE bp_amortissement ADD CONSTRAINT FK_39D8AEA48DEE6016 FOREIGN KEY (id_country) REFERENCES bp_country (id)');
        $this->addSql('ALTER TABLE bp_bfr ADD CONSTRAINT FK_58BD33B6A76ED395 FOREIGN KEY (user_id) REFERENCES user_user (id)');
        $this->addSql('ALTER TABLE bp_bfr ADD CONSTRAINT FK_58BD33B685B7937E FOREIGN KEY (businessPlan_id) REFERENCES bp_bp (id)');
        $this->addSql('ALTER TABLE bp_bp ADD CONSTRAINT FK_2EC16238A76ED395 FOREIGN KEY (user_id) REFERENCES user_user (id)');
        $this->addSql('ALTER TABLE bp_bp ADD CONSTRAINT FK_2EC16238ED5CA9E6 FOREIGN KEY (service_id) REFERENCES bp_service (id)');
        $this->addSql('ALTER TABLE bp_cart ADD CONSTRAINT FK_1AC380C2A76ED395 FOREIGN KEY (user_id) REFERENCES user_user (id)');
        $this->addSql('ALTER TABLE bp_cart ADD CONSTRAINT FK_1AC380C285B7937E FOREIGN KEY (businessPlan_id) REFERENCES bp_bp (id)');
        $this->addSql('ALTER TABLE bp_cart ADD CONSTRAINT FK_1AC380C266C5951B FOREIGN KEY (coupon_id) REFERENCES promotion_coupon (id)');
        $this->addSql('ALTER TABLE bp_cart ADD CONSTRAINT FK_1AC380C24C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id)');
        $this->addSql('ALTER TABLE bp_charge ADD CONSTRAINT FK_9F8B0D585B7937E FOREIGN KEY (businessPlan_id) REFERENCES bp_bp (id)');
        $this->addSql('ALTER TABLE bp_charge ADD CONSTRAINT FK_9F8B0D5EA6C58B7 FOREIGN KEY (chargeLabel_id) REFERENCES bp_charge_label (id)');
        $this->addSql('ALTER TABLE bp_charge_label_translation ADD CONSTRAINT FK_482B3EC52C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES bp_charge_label (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bp_exercice ADD CONSTRAINT FK_B9A78D0E85B7937E FOREIGN KEY (businessPlan_id) REFERENCES bp_bp (id)');
        $this->addSql('ALTER TABLE bp_funding ADD CONSTRAINT FK_45C902C85B7937E FOREIGN KEY (businessPlan_id) REFERENCES bp_bp (id)');
        $this->addSql('ALTER TABLE bp_funding ADD CONSTRAINT FK_45C902CEA6C58B7 FOREIGN KEY (chargeLabel_id) REFERENCES bp_charge_label (id)');
        $this->addSql('ALTER TABLE bp_income ADD CONSTRAINT FK_633B7631A76ED395 FOREIGN KEY (user_id) REFERENCES user_user (id)');
        $this->addSql('ALTER TABLE bp_income ADD CONSTRAINT FK_633B763185B7937E FOREIGN KEY (businessPlan_id) REFERENCES bp_bp (id)');
        $this->addSql('ALTER TABLE bp_info_charge ADD CONSTRAINT FK_BB22C13489D40298 FOREIGN KEY (exercice_id) REFERENCES bp_exercice (id)');
        $this->addSql('ALTER TABLE bp_info_charge ADD CONSTRAINT FK_BB22C13455284914 FOREIGN KEY (charge_id) REFERENCES bp_charge (id)');
        $this->addSql('ALTER TABLE bp_info_product ADD CONSTRAINT FK_D3A44DC8F347EFB FOREIGN KEY (produit_id) REFERENCES bp_produit (id)');
        $this->addSql('ALTER TABLE bp_info_product ADD CONSTRAINT FK_D3A44DC889D40298 FOREIGN KEY (exercice_id) REFERENCES bp_exercice (id)');
        $this->addSql('ALTER TABLE bp_information ADD CONSTRAINT FK_AED22D564D218E FOREIGN KEY (location_id) REFERENCES bp_location (id)');
        $this->addSql('ALTER TABLE bp_information ADD CONSTRAINT FK_AED22D5F5B7AF75 FOREIGN KEY (address_id) REFERENCES bp_address (id)');
        $this->addSql('ALTER TABLE bp_information ADD CONSTRAINT FK_AED22D5A76ED395 FOREIGN KEY (user_id) REFERENCES user_user (id)');
        $this->addSql('ALTER TABLE bp_information ADD CONSTRAINT FK_AED22D585B7937E FOREIGN KEY (businessPlan_id) REFERENCES bp_bp (id)');
        $this->addSql('ALTER TABLE bp_information ADD CONSTRAINT FK_AED22D5854E9F19 FOREIGN KEY (legalForm_id) REFERENCES bp_legal_form (id)');
        $this->addSql('ALTER TABLE bp_investissement ADD CONSTRAINT FK_21C9504EA6C58B7 FOREIGN KEY (chargeLabel_id) REFERENCES bp_charge_label (id)');
        $this->addSql('ALTER TABLE bp_investissement ADD CONSTRAINT FK_21C950485B7937E FOREIGN KEY (businessPlan_id) REFERENCES bp_bp (id)');
        $this->addSql('ALTER TABLE legal_form_country ADD CONSTRAINT FK_B507BD1EDA79932F FOREIGN KEY (id_legal_form) REFERENCES bp_legal_form (id)');
        $this->addSql('ALTER TABLE legal_form_country ADD CONSTRAINT FK_B507BD1E8DEE6016 FOREIGN KEY (id_country) REFERENCES bp_country (id)');
        $this->addSql('ALTER TABLE pole_translation ADD CONSTRAINT FK_19E38852C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES bp_pole_staff (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bp_produit ADD CONSTRAINT FK_FEF4ADDD85B7937E FOREIGN KEY (businessPlan_id) REFERENCES bp_bp (id)');
        $this->addSql('ALTER TABLE bp_rate ADD CONSTRAINT FK_CE8C374CC54C8C93 FOREIGN KEY (type_id) REFERENCES bp_rate_label (id)');
        $this->addSql('ALTER TABLE bp_rate ADD CONSTRAINT FK_CE8C374CF92F3E70 FOREIGN KEY (country_id) REFERENCES bp_country (id)');
        $this->addSql('ALTER TABLE bp_saisonnalite ADD CONSTRAINT FK_DB3F488B85B7937E FOREIGN KEY (businessPlan_id) REFERENCES bp_bp (id)');
        $this->addSql('ALTER TABLE bp_service ADD CONSTRAINT FK_36CCDB28FC33D2FD FOREIGN KEY (bpCatalogKind_id) REFERENCES promotion_catalog (id)');
        $this->addSql('ALTER TABLE bp_staff ADD CONSTRAINT FK_6210162985B7937E FOREIGN KEY (businessPlan_id) REFERENCES bp_bp (id)');
        $this->addSql('ALTER TABLE bp_staff ADD CONSTRAINT FK_62101629419C3385 FOREIGN KEY (pole_id) REFERENCES bp_pole_staff (id)');
        $this->addSql('ALTER TABLE bp_staff ADD CONSTRAINT FK_621016296BF700BD FOREIGN KEY (status_id) REFERENCES bp_status (id)');
        $this->addSql('ALTER TABLE status_translation ADD CONSTRAINT FK_B0B3309E2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES bp_status (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE join_cart_catalog ADD CONSTRAINT FK_F95EC5191AD5CDBF FOREIGN KEY (cart_id) REFERENCES bp_cart (id)');
        $this->addSql('ALTER TABLE join_cart_catalog ADD CONSTRAINT FK_F95EC519CC3C66FC FOREIGN KEY (catalog_id) REFERENCES promotion_catalog (id)');
        $this->addSql('ALTER TABLE promotion_coupon ADD CONSTRAINT FK_7105143F9393F8FE FOREIGN KEY (partner_id) REFERENCES partners_partner (id)');
        $this->addSql('ALTER TABLE coupon_user ADD CONSTRAINT FK_CDAD0A4B66C5951B FOREIGN KEY (coupon_id) REFERENCES promotion_coupon (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE coupon_user ADD CONSTRAINT FK_CDAD0A4BA76ED395 FOREIGN KEY (user_id) REFERENCES user_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_social_charge ADD CONSTRAINT FK_A5AE6BB8F92F3E70 FOREIGN KEY (country_id) REFERENCES bp_country (id)');
        $this->addSql('ALTER TABLE user_social_charge ADD CONSTRAINT FK_A5AE6BB86BF700BD FOREIGN KEY (status_id) REFERENCES bp_status (id)');
        $this->addSql('ALTER TABLE user_user ADD CONSTRAINT FK_F7129A809393F8FE FOREIGN KEY (partner_id) REFERENCES partners_partner (id)');
        $this->addSql('ALTER TABLE pitch_business_model ADD CONSTRAINT FK_7FEB5156FEEFC64B FOREIGN KEY (pitch_id) REFERENCES pitch (id)');
        $this->addSql('ALTER TABLE pitch_cart ADD CONSTRAINT FK_3449185A76ED395 FOREIGN KEY (user_id) REFERENCES user_user (id)');
        $this->addSql('ALTER TABLE pitch_cart ADD CONSTRAINT FK_3449185FEEFC64B FOREIGN KEY (pitch_id) REFERENCES pitch (id)');
        $this->addSql('ALTER TABLE pitch_competitor ADD CONSTRAINT FK_812C40C6808BBBF5 FOREIGN KEY (concurrence_id) REFERENCES pitch_concurrence (id)');
        $this->addSql('ALTER TABLE pitch_concurrence ADD CONSTRAINT FK_4AEC9B0FFEEFC64B FOREIGN KEY (pitch_id) REFERENCES pitch (id)');
        $this->addSql('ALTER TABLE pitch_indicator ADD CONSTRAINT FK_43B0226DFEEFC64B FOREIGN KEY (pitch_id) REFERENCES pitch (id)');
        $this->addSql('ALTER TABLE pitch_information ADD CONSTRAINT FK_6D1CCC8B854E9F19 FOREIGN KEY (legalForm_id) REFERENCES bp_legal_form (id)');
        $this->addSql('ALTER TABLE pitch_information ADD CONSTRAINT FK_6D1CCC8BFEEFC64B FOREIGN KEY (pitch_id) REFERENCES pitch (id)');
        $this->addSql('ALTER TABLE pitch ADD CONSTRAINT FK_279FBED9A76ED395 FOREIGN KEY (user_id) REFERENCES user_user (id)');
        $this->addSql('ALTER TABLE promotion_catalog_pitch ADD CONSTRAINT FK_7E3591FFEEFC64B FOREIGN KEY (pitch_id) REFERENCES pitch (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE promotion_catalog_pitch ADD CONSTRAINT FK_7E3591FCC3C66FC FOREIGN KEY (catalog_id) REFERENCES promotion_catalog (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pitch_strategy ADD CONSTRAINT FK_42770021FEEFC64B FOREIGN KEY (pitch_id) REFERENCES pitch (id)');
        $this->addSql('ALTER TABLE pitch_swot ADD CONSTRAINT FK_B49A75C4FEEFC64B FOREIGN KEY (pitch_id) REFERENCES pitch (id)');
        $this->addSql('ALTER TABLE pitch_team ADD CONSTRAINT FK_CC07BF2DFEEFC64B FOREIGN KEY (pitch_id) REFERENCES pitch (id)');
        $this->addSql('ALTER TABLE lexik_trans_unit_translations ADD CONSTRAINT FK_B0AA394493CB796C FOREIGN KEY (file_id) REFERENCES lexik_translation_file (id)');
        $this->addSql('ALTER TABLE lexik_trans_unit_translations ADD CONSTRAINT FK_B0AA3944C3C583C9 FOREIGN KEY (trans_unit_id) REFERENCES lexik_trans_unit (id)');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE back_benefit_translation DROP FOREIGN KEY FK_15B275912C2AC5D3');
        $this->addSql('ALTER TABLE back_concept_translation DROP FOREIGN KEY FK_5ADDF0F72C2AC5D3');
        $this->addSql('ALTER TABLE back_definition DROP FOREIGN KEY FK_A6BC8910F909284E');
        $this->addSql('ALTER TABLE back_definition_translation DROP FOREIGN KEY FK_E91481A62C2AC5D3');
        $this->addSql('ALTER TABLE back_page_translation DROP FOREIGN KEY FK_9DB75F3B2C2AC5D3');
        $this->addSql('ALTER TABLE back_document DROP FOREIGN KEY FK_22BDDDF64584665A');
        $this->addSql('ALTER TABLE back_product_translation DROP FOREIGN KEY FK_132F6B692C2AC5D3');
        $this->addSql('ALTER TABLE blog_post DROP FOREIGN KEY FK_BA5AE01D12469DE2');
        $this->addSql('ALTER TABLE post_translation DROP FOREIGN KEY FK_5829CF402C2AC5D3');
        $this->addSql('ALTER TABLE bp_information DROP FOREIGN KEY FK_AED22D5F5B7AF75');
        $this->addSql('ALTER TABLE bp_bfr DROP FOREIGN KEY FK_58BD33B685B7937E');
        $this->addSql('ALTER TABLE bp_cart DROP FOREIGN KEY FK_1AC380C285B7937E');
        $this->addSql('ALTER TABLE bp_charge DROP FOREIGN KEY FK_9F8B0D585B7937E');
        $this->addSql('ALTER TABLE bp_exercice DROP FOREIGN KEY FK_B9A78D0E85B7937E');
        $this->addSql('ALTER TABLE bp_funding DROP FOREIGN KEY FK_45C902C85B7937E');
        $this->addSql('ALTER TABLE bp_income DROP FOREIGN KEY FK_633B763185B7937E');
        $this->addSql('ALTER TABLE bp_information DROP FOREIGN KEY FK_AED22D585B7937E');
        $this->addSql('ALTER TABLE bp_investissement DROP FOREIGN KEY FK_21C950485B7937E');
        $this->addSql('ALTER TABLE bp_produit DROP FOREIGN KEY FK_FEF4ADDD85B7937E');
        $this->addSql('ALTER TABLE bp_saisonnalite DROP FOREIGN KEY FK_DB3F488B85B7937E');
        $this->addSql('ALTER TABLE bp_staff DROP FOREIGN KEY FK_6210162985B7937E');
        $this->addSql('ALTER TABLE join_cart_catalog DROP FOREIGN KEY FK_F95EC5191AD5CDBF');
        $this->addSql('ALTER TABLE bp_info_charge DROP FOREIGN KEY FK_BB22C13455284914');
        $this->addSql('ALTER TABLE bp_amortissement DROP FOREIGN KEY FK_39D8AEA43B4229B2');
        $this->addSql('ALTER TABLE bp_charge DROP FOREIGN KEY FK_9F8B0D5EA6C58B7');
        $this->addSql('ALTER TABLE bp_charge_label_translation DROP FOREIGN KEY FK_482B3EC52C2AC5D3');
        $this->addSql('ALTER TABLE bp_funding DROP FOREIGN KEY FK_45C902CEA6C58B7');
        $this->addSql('ALTER TABLE bp_investissement DROP FOREIGN KEY FK_21C9504EA6C58B7');
        $this->addSql('ALTER TABLE back_document DROP FOREIGN KEY FK_22BDDDF6F92F3E70');
        $this->addSql('ALTER TABLE bp_address DROP FOREIGN KEY FK_DA1F2E7BF92F3E70');
        $this->addSql('ALTER TABLE bp_amortissement DROP FOREIGN KEY FK_39D8AEA48DEE6016');
        $this->addSql('ALTER TABLE legal_form_country DROP FOREIGN KEY FK_B507BD1E8DEE6016');
        $this->addSql('ALTER TABLE bp_rate DROP FOREIGN KEY FK_CE8C374CF92F3E70');
        $this->addSql('ALTER TABLE user_social_charge DROP FOREIGN KEY FK_A5AE6BB8F92F3E70');
        $this->addSql('ALTER TABLE bp_info_charge DROP FOREIGN KEY FK_BB22C13489D40298');
        $this->addSql('ALTER TABLE bp_info_product DROP FOREIGN KEY FK_D3A44DC889D40298');
        $this->addSql('ALTER TABLE bp_information DROP FOREIGN KEY FK_AED22D5854E9F19');
        $this->addSql('ALTER TABLE legal_form_country DROP FOREIGN KEY FK_B507BD1EDA79932F');
        $this->addSql('ALTER TABLE pitch_information DROP FOREIGN KEY FK_6D1CCC8B854E9F19');
        $this->addSql('ALTER TABLE bp_information DROP FOREIGN KEY FK_AED22D564D218E');
        $this->addSql('ALTER TABLE pole_translation DROP FOREIGN KEY FK_19E38852C2AC5D3');
        $this->addSql('ALTER TABLE bp_staff DROP FOREIGN KEY FK_62101629419C3385');
        $this->addSql('ALTER TABLE bp_info_product DROP FOREIGN KEY FK_D3A44DC8F347EFB');
        $this->addSql('ALTER TABLE bp_rate DROP FOREIGN KEY FK_CE8C374CC54C8C93');
        $this->addSql('ALTER TABLE bp_bp DROP FOREIGN KEY FK_2EC16238ED5CA9E6');
        $this->addSql('ALTER TABLE bp_staff DROP FOREIGN KEY FK_621016296BF700BD');
        $this->addSql('ALTER TABLE status_translation DROP FOREIGN KEY FK_B0B3309E2C2AC5D3');
        $this->addSql('ALTER TABLE user_social_charge DROP FOREIGN KEY FK_A5AE6BB86BF700BD');
        $this->addSql('ALTER TABLE back_benefit DROP FOREIGN KEY FK_87E1E301CC3C66FC');
        $this->addSql('ALTER TABLE bp_service DROP FOREIGN KEY FK_36CCDB28FC33D2FD');
        $this->addSql('ALTER TABLE join_cart_catalog DROP FOREIGN KEY FK_F95EC519CC3C66FC');
        $this->addSql('ALTER TABLE promotion_catalog_pitch DROP FOREIGN KEY FK_7E3591FCC3C66FC');
        $this->addSql('ALTER TABLE bp_cart DROP FOREIGN KEY FK_1AC380C266C5951B');
        $this->addSql('ALTER TABLE coupon_user DROP FOREIGN KEY FK_CDAD0A4B66C5951B');
        $this->addSql('ALTER TABLE bp_address DROP FOREIGN KEY FK_DA1F2E7BA76ED395');
        $this->addSql('ALTER TABLE bp_bfr DROP FOREIGN KEY FK_58BD33B6A76ED395');
        $this->addSql('ALTER TABLE bp_bp DROP FOREIGN KEY FK_2EC16238A76ED395');
        $this->addSql('ALTER TABLE bp_cart DROP FOREIGN KEY FK_1AC380C2A76ED395');
        $this->addSql('ALTER TABLE bp_income DROP FOREIGN KEY FK_633B7631A76ED395');
        $this->addSql('ALTER TABLE bp_information DROP FOREIGN KEY FK_AED22D5A76ED395');
        $this->addSql('ALTER TABLE coupon_user DROP FOREIGN KEY FK_CDAD0A4BA76ED395');
        $this->addSql('ALTER TABLE pitch_cart DROP FOREIGN KEY FK_3449185A76ED395');
        $this->addSql('ALTER TABLE pitch DROP FOREIGN KEY FK_279FBED9A76ED395');
        $this->addSql('ALTER TABLE pitch_competitor DROP FOREIGN KEY FK_812C40C6808BBBF5');
        $this->addSql('ALTER TABLE pitch_business_model DROP FOREIGN KEY FK_7FEB5156FEEFC64B');
        $this->addSql('ALTER TABLE pitch_cart DROP FOREIGN KEY FK_3449185FEEFC64B');
        $this->addSql('ALTER TABLE pitch_concurrence DROP FOREIGN KEY FK_4AEC9B0FFEEFC64B');
        $this->addSql('ALTER TABLE pitch_indicator DROP FOREIGN KEY FK_43B0226DFEEFC64B');
        $this->addSql('ALTER TABLE pitch_information DROP FOREIGN KEY FK_6D1CCC8BFEEFC64B');
        $this->addSql('ALTER TABLE promotion_catalog_pitch DROP FOREIGN KEY FK_7E3591FFEEFC64B');
        $this->addSql('ALTER TABLE pitch_strategy DROP FOREIGN KEY FK_42770021FEEFC64B');
        $this->addSql('ALTER TABLE pitch_swot DROP FOREIGN KEY FK_B49A75C4FEEFC64B');
        $this->addSql('ALTER TABLE pitch_team DROP FOREIGN KEY FK_CC07BF2DFEEFC64B');
        $this->addSql('ALTER TABLE bp_cart DROP FOREIGN KEY FK_1AC380C24C3A3BB');
        $this->addSql('ALTER TABLE promotion_coupon DROP FOREIGN KEY FK_7105143F9393F8FE');
        $this->addSql('ALTER TABLE user_user DROP FOREIGN KEY FK_F7129A809393F8FE');
        $this->addSql('ALTER TABLE lexik_trans_unit_translations DROP FOREIGN KEY FK_B0AA394493CB796C');
        $this->addSql('ALTER TABLE lexik_trans_unit_translations DROP FOREIGN KEY FK_B0AA3944C3C583C9');
        $this->addSql('DROP TABLE ext_translations');
        $this->addSql('DROP TABLE ext_log_entries');
        $this->addSql('DROP TABLE back_benefit');
        $this->addSql('DROP TABLE back_benefit_translation');
        $this->addSql('DROP TABLE back_concept');
        $this->addSql('DROP TABLE back_concept_translation');
        $this->addSql('DROP TABLE back_contact');
        $this->addSql('DROP TABLE back_definition');
        $this->addSql('DROP TABLE back_definition_translation');
        $this->addSql('DROP TABLE back_document');
        $this->addSql('DROP TABLE back_page');
        $this->addSql('DROP TABLE back_page_translation');
        $this->addSql('DROP TABLE back_partner');
        $this->addSql('DROP TABLE back_press');
        $this->addSql('DROP TABLE back_product');
        $this->addSql('DROP TABLE back_product_translation');
        $this->addSql('DROP TABLE back_testimonials');
        $this->addSql('DROP TABLE back_introsection');
        $this->addSql('DROP TABLE blog_category');
        $this->addSql('DROP TABLE blog_post');
        $this->addSql('DROP TABLE post_translation');
        $this->addSql('DROP TABLE bp_address');
        $this->addSql('DROP TABLE bp_amortissement');
        $this->addSql('DROP TABLE bp_bfr');
        $this->addSql('DROP TABLE bp_bp');
        $this->addSql('DROP TABLE bp_cart');
        $this->addSql('DROP TABLE bp_charge');
        $this->addSql('DROP TABLE bp_charge_label');
        $this->addSql('DROP TABLE bp_charge_label_translation');
        $this->addSql('DROP TABLE bp_country');
        $this->addSql('DROP TABLE bp_exercice');
        $this->addSql('DROP TABLE bp_funding');
        $this->addSql('DROP TABLE bp_income');
        $this->addSql('DROP TABLE bp_info_charge');
        $this->addSql('DROP TABLE bp_info_product');
        $this->addSql('DROP TABLE bp_information');
        $this->addSql('DROP TABLE bp_investissement');
        $this->addSql('DROP TABLE bp_legal_form');
        $this->addSql('DROP TABLE legal_form_country');
        $this->addSql('DROP TABLE bp_location');
        $this->addSql('DROP TABLE page');
        $this->addSql('DROP TABLE bp_pole_staff');
        $this->addSql('DROP TABLE pole_translation');
        $this->addSql('DROP TABLE bp_produit');
        $this->addSql('DROP TABLE bp_rate');
        $this->addSql('DROP TABLE bp_rate_label');
        $this->addSql('DROP TABLE bp_saisonnalite');
        $this->addSql('DROP TABLE bp_service');
        $this->addSql('DROP TABLE bp_smic');
        $this->addSql('DROP TABLE bp_staff');
        $this->addSql('DROP TABLE bp_status');
        $this->addSql('DROP TABLE status_translation');
        $this->addSql('DROP TABLE promotion_catalog');
        $this->addSql('DROP TABLE join_cart_catalog');
        $this->addSql('DROP TABLE promotion_coupon');
        $this->addSql('DROP TABLE coupon_user');
        $this->addSql('DROP TABLE user_social_charge');
        $this->addSql('DROP TABLE user_user');
        $this->addSql('DROP TABLE pitch_business_model');
        $this->addSql('DROP TABLE pitch_cart');
        $this->addSql('DROP TABLE pitch_competitor');
        $this->addSql('DROP TABLE pitch_concurrence');
        $this->addSql('DROP TABLE pitch_indicator');
        $this->addSql('DROP TABLE pitch_information');
        $this->addSql('DROP TABLE pitch');
        $this->addSql('DROP TABLE promotion_catalog_pitch');
        $this->addSql('DROP TABLE pitch_strategy');
        $this->addSql('DROP TABLE pitch_swot');
        $this->addSql('DROP TABLE pitch_team');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE partners_partner');
        $this->addSql('DROP TABLE lexik_translation_file');
        $this->addSql('DROP TABLE lexik_trans_unit_translations');
        $this->addSql('DROP TABLE lexik_trans_unit');
    }
}
