<?php

namespace BackBundle\Repository;

/**
 * DefinitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefinitionRepository extends \Doctrine\ORM\EntityRepository
{
}
