<?php

namespace BackBundle\Repository;

/**
 * PlanooOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoorneyOrderRepository extends \Doctrine\ORM\EntityRepository {
    
}
