<?php

namespace BackBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAllIntro()
    {
        $q = $this->createQueryBuilder("t")
            ->where('t.published = true')
        ;

        $q = $q->getQuery();

        return $q->getResult();

    }

}
