<?php

namespace BackBundle\Repository;

/**
 * TestimonialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestimonialsRepository extends \Doctrine\ORM\EntityRepository
{
}
