<?php

namespace PaymentBundle\Repository;

use DateTime;
use PaymentBundle\Entity\Payment;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends \Doctrine\ORM\EntityRepository {

    public function getMyPayments($user) {

        $q = $this->createQueryBuilder("p")
            ->leftJoin('p.cart', 'cart')
            ->where('cart.user = :idUser')
            ->setParameter('idUser', $user->getId());

        $preparedQuery = $q->getQuery();
        return $preparedQuery->getResult();
    }

    public function getEndedTrial() {

        $date = new DateTime();
        $date->sub(new \DateInterval('P6D'));

        $q = $this->createQueryBuilder("p")
            ->where('p.paymentDate <= :date')
            ->andWhere('p.statut = :statut')
            ->setParameter('statut', Payment::PAYMENT_STATUT_CAPTURED)
            ->setParameter('date', $date->format("Y-m-d") . " 23:59:59")
        ;

        $preparedQuery = $q->getQuery();
        return $preparedQuery->getResult();
    }

}
