back_benefit_index:
    path:     /
    defaults: { _controller: "BackBundle:Benefit:index" }
    methods:  GET

back_benefit_show:
    path:     /{id}/show
    defaults: { _controller: "BackBundle:Benefit:show" }
    methods:  GET

back_benefit_new:
    path:     /new
    defaults: { _controller: "BackBundle:Benefit:new" }
    methods:  [GET, POST]

back_benefit_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackBundle:Benefit:edit" }
    methods:  [GET, POST]

back_benefit_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackBundle:Benefit:delete" }
    methods:  DELETE
