back_socialcharge_index:
    path:     /
    defaults: { _controller: "BackBundle:SocialCharge:index" }
    methods:  GET

back_socialcharge_show:
    path:     /{id}/show
    defaults: { _controller: "BackBundle:SocialCharge:show" }
    methods:  GET

back_socialcharge_new:
    path:     /new
    defaults: { _controller: "BackBundle:SocialCharge:new" }
    methods:  [GET, POST]

back_socialcharge_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackBundle:SocialCharge:edit" }
    methods:  [GET, POST]

back_socialcharge_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackBundle:SocialCharge:delete" }
    methods:  DELETE

back_socialcharge_deleted:
    path:     /remove/{id}
    defaults: { _controller: "BackBundle:SocialCharge:deleted" }
