<?php

namespace BPBundle\Repository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends \Doctrine\ORM\EntityRepository {

    public function listAllCategories() {
        $q = $this->_em->createQueryBuilder()
                ->select('category');

        $q = $q->getQuery();

        return $q->getResult();
    }

}
