<?php

namespace BPBundle\Repository;

/**
 * AmortissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmortissementRepository extends \Doctrine\ORM\EntityRepository
{
}
