<?php

namespace BPBundle\Repository;

/**
 * BfrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BfrRepository extends \Doctrine\ORM\EntityRepository
{
}
