<?php

namespace BPBundle\Repository;

/**
 * ChargeLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChargeLabelRepository extends \Doctrine\ORM\EntityRepository
{
    public function getChargeType($type)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.type = :type')

            ->setParameter('type', $type);

        return $qb;
    }

    public function MyFindAllDesc()
    {
        $q = $this->createQueryBuilder("cl")
            ->orderBy('cl.translate.name', 'asc')
        ;

        $q = $q->getQuery();

        return $q->getResult();

    }
}
