<?php

namespace BPBundle\Repository;

/**
 * CountryRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRateRepository extends \Doctrine\ORM\EntityRepository
{
}
