<?php

namespace BPBundle\Repository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \Doctrine\ORM\EntityRepository
{
    public function MyFindAllByCountry()
    {
        $q = $this->createQueryBuilder("c")
            ->leftJoin("c.rates", "r")
            ->addSelect("r")
            ->addOrderBy('c.name', 'ASC')
        ;

        $q = $q->getQuery();

        return $q->getResult();

    }

}
