<?php

namespace BPBundle\Repository;

/**
 * CustomWritingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomWritingRepository extends \Doctrine\ORM\EntityRepository
{
}
