<?php

namespace BPBundle\Repository;

/**
 * InformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationRepository extends \Doctrine\ORM\EntityRepository
{
    public function MyFindDateCloseBy($id) {

        $q = $this->_em->createQueryBuilder()
            ->select('i.closingDate')
            ->from('BPBundle:Information', 'i')
            ->where('i.id = :id')

            ->setParameter('id', $id)
        ;

        $q = $q->getQuery();

        return $q->getSingleResult();
    }

}
