<?php

namespace BPBundle\Repository;

/**
 * InfoProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function MyFindBy($id)
    {
        $q = $this->createQueryBuilder("ip")
            ->leftJoin("ip.product", "p")
            ->addSelect("p")
            ->where('p.product = :id')

            ->setParameter('id', $id)
        ;

        $q = $q->getQuery();

        return $q->getResult();

    }
}
