<?php

namespace BPBundle\Repository;

/**
 * InfoChargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoChargeRepository extends \Doctrine\ORM\EntityRepository
{
}
