<?php

namespace BPBundle\Repository;

/**
 * InvestissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvestissementRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAllByBusinessPlan($bp)
    {
        $q = $this->createQueryBuilder("i")
            ->leftJoin("i.businessPlan", "bp")
            ->addSelect("bp")
            ->where('i.businessPlan = :bp')

            ->setParameter('bp', $bp)
        ;

        $q = $q->getQuery();

        return $q->getResult();

    }
}
