<?php

namespace BPBundle\Repository;

/**
 * LegalFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegalFormRepository extends \Doctrine\ORM\EntityRepository {

    public function findByCountry($idCountry) {

        $q = $this->_em->createQueryBuilder()
                ->select('lf.id, lf.code, lf.name')
                ->from('BPBundle:LegalForm', 'lf')
                ->leftJoin('lf.countries', 'c')
                ->where('c.id = :idCountry')
                ->andWhere('lf.id <> 0')
                ->setParameter('idCountry', $idCountry)
        ;

        $q = $q->getQuery();

        return $q->getResult();
    }

}
