<?php

namespace BPBundle\Repository;

/**
 * MarketStudyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketStudyRepository extends \Doctrine\ORM\EntityRepository
{
}
