<?php

namespace BPBundle\Repository;

/**
 * PoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoleRepository extends \Doctrine\ORM\EntityRepository {

    public function myFindAll() {
        $q = $this->createQueryBuilder("p")
                ->join("p.translations", "t")
                ->addOrderBy('t.name', 'ASC')
                ->where('t.id <>6');
        ;


        return $q;
    }

}
