<?php

namespace BPBundle\Repository;

/**
 * ProductStockSeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductStockSeasonRepository extends \Doctrine\ORM\EntityRepository
{
}
