<?php

namespace BPBundle\Repository;

/**
 * ProductSeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductSeasonRepository extends \Doctrine\ORM\EntityRepository
{
}
