<?php

namespace BPBundle\Repository;

/**
 * RateLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateLabelRepository extends \Doctrine\ORM\EntityRepository
{
}
