<?php

namespace BPBundle\Repository;

/**
 * SaisonnaliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisonnaliteRepository extends \Doctrine\ORM\EntityRepository
{
}
