<?php

namespace BPBundle\Repository;

/**
 * SmicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmicRepository extends \Doctrine\ORM\EntityRepository
{
}
