<?php

namespace BPBundle\Repository;

/**
 * StaffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaffRepository extends \Doctrine\ORM\EntityRepository
{
    public function MyFindAllByBusinessPlan($bp)
    {
        $q = $this->createQueryBuilder("s")
            ->leftJoin("s.businessPlan", "bp")
            ->addSelect("bp")
            ->where('s.businessPlan = :bp')

            ->setParameter('bp', $bp)
        ;

        $q = $q->getQuery();

        return $q->getResult();

    }
}
