<?php

namespace BPBundle\Repository;

/**
 * StaffPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaffPositionRepository extends \Doctrine\ORM\EntityRepository
{
}
