<?php

namespace BPBundle\Repository;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll()
    {
        $q = $this->createQueryBuilder("p")
            ->join("p.translations", "t")
            ->addOrderBy('t.name', 'ASC');

        return $q;
    }
}
