back_pole_index:
    path:     /
    defaults: { _controller: "BPBundle:Backend/Pole:index" }
    methods:  GET

back_pole_new:
    path:     /new
    defaults: { _controller: "BPBundle:Backend/Pole:new" }
    methods:  [GET, POST]

back_pole_edit:
    path:     /{id}/edit
    defaults: { _controller: "BPBundle:Backend/Pole:edit" }
    methods:  [GET, POST]

back_pole_delete:
    path:     /{id}/delete
    defaults: { _controller: "BPBundle:Backend/Pole:delete" }
    methods:  DELETE

back_pole_deleted:
    path:     /remove/{id}
    defaults: { _controller: "BPBundle:Backend/Pole:deleted" }
